test_manager_1 = Manager.create(email: "gekijo@gmail.com", password: "gekigekijojo1", password_confirmation: "gekigekijojo1", studio_name: "劇場劇場", studio_name_kana: "げきじょうげきじょう")
test_manager_2 = Manager.create(email: "geikan@gmail.com", password: "geigeikankan1", password_confirmation: "geigeikankan1", studio_name: "芸館芸館", studio_name_kana: "げいかんげいかん")

Bday.create!(bday: "日")
Bday.create!(bday: "月")
Bday.create!(bday: "火")
Bday.create!(bday: "水")
Bday.create!(bday: "木")
Bday.create!(bday: "金")
Bday.create!(bday: "土")